---
title: "R Notebook"
output: html_notebook
---




1. Read the cleaned data into R.

```{r}
library(tidyverse)
```

```{r}
meteorite_landings <- read_csv("meteorite_landings_clean.csv")
```

2. Find the names and years found for the 10 largest meteorites in the data.

```{r}
largest_by_year <- meteorite_landings %>% 
  slice_max(mass_g, n = 10) %>% 
  group_by(name, year)
largest_by_year
```

3. Find the average mass of meteorites that were recorded falling, vs. those which were just found.
```{r}
mean_mass_falling <- meteorite_landings %>% 
  filter(fall == "Fell") %>%
    summarise(average_mass_fell = mean(mass_g))
    
```

```{r}
mean_mass_not_falling <- meteorite_landings %>% 
  filter(fall != "Fell") %>%
    summarise(average_mass_no_fall = mean(mass_g))
```

```{r}
paste(mean_mass_falling, "vs", mean_mass_not_falling)
```

4. Find the number of meteorites in each year, for every year since 2000.
```{r}
number_per_year <- meteorite_landings %>% 
  filter(year >= 2000) %>%
  group_by(year) %>% 
  tally()
  
```

